apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendservice
  labels:
    app: frontendservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendservice
  template:
    metadata:
      labels:
        app: frontendservice
    spec:
      serviceAccountName: google-boutique
      containers:
        - name: frontendservice
          image: ashwiniethiraj/frontendservice:v1
          ports:
            - containerPort: 8080
          env:
            - name: AD_SERVICE_ADDR
              value: adservice:9555
            - name: RECOMMENDATION_SERVICE_ADDR
              value: recommendationservice:8080
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: CART_SERVICE_ADDR
              value: cartservice:7070
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:7000
            - name: CHECKOUT_SERVICE_ADDR
              value: checkoutservice:5050
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:50051
            - name: EMAIL_SERVICE_ADDR
              value: emailservice:8080
            - name: PAYMENT_SERVICE_ADDR
              value: paymentservice:8086
            - name: DISABLE_PROFILER
              value: "true"
         
      imagePullSecrets:
        - name: ecr-secret
