apiVersion: v1
kind: Service
metadata:
 name: paymentservice
 labels: 
   app: paymentservice

spec:
 type: ClusterIP
 ports:
  - name: http
    port: 8086
    targetPort: 8086
 selector: 
   app: paymentservice
