apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      serviceAccountName: google-boutique
      containers:
        - name: emailservice
          image: ashwiniethiraj/emailservice:v1
          ports:
            - containerPort: 8080
          env:
            - name: DISABLE_PROFILER
              value: "true"
          
      imagePullSecrets:
        - name: ecr-secret
