apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: google-boutique
      containers:
        - name: checkoutservice
          image: ashwiniethiraj/checkoutservice:18914475242
          ports:
            - containerPort: 5050
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: CART_SERVICE_ADDR
              value: cartservice:7070
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:7000
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:50051
            - name: PAYMENT_SERVICE_ADDR
              value: paymentservice:8086
            - name: EMAIL_SERVICE_ADDR
              value: emailservice:8080
            - name: DISABLE_PROFILER
              value: "true"
          
      imagePullSecrets:
        - name: ecr-secret
