apiVersion: v1
kind: Service
metadata:
 name: checkoutservice
 labels: 
   app: checkoutservice

spec:
 type: ClusterIP
 ports:
  - name: grpc
    port: 5050
    targetPort: 5050
 selector: 
   app: checkoutservice
