apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: google-boutique
      containers:
        - name: adservice
          image: ashwiniethiraj/adservices:18911652720
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
            - name: DISABLE_PROFILER
              value: "true"
  
      imagePullSecrets:
        - name: ecr-secret
