apiVersion: v1
kind: Service
metadata:
 name: shippingservice
 labels: 
   app: shippingservice

spec:
 type: ClusterIP
 ports:
  - name: grpc
    port: 50051
    targetPort: 50051
 selector: 
   app: shippingservice
