apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: google-boutique
      containers:
        - name: currencyservice
<<<<<<< Updated upstream
          image: ashwiniethiraj/currencyservice:18927877660
=======
          image: ashwiniethiraj/currencyservice:18927877660
>>>>>>> Stashed changes
          ports:
            - containerPort: 7000
          env:
            - name: DISABLE_PROFILER
              value: "true"
         
      imagePullSecrets:
        - name: ecr-secret
