apiVersion: v1
kind: Service
metadata:
 name: productcatalogservice
 labels: 
   app: productcatalogservice

spec:
 type: ClusterIP
 ports:
  - name: grpc
    port: 3550
    targetPort: 3550
 selector: 
   app: productcatalogservice
