apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      serviceAccountName: google-boutique
      containers:
        - name: recommendationservice
          image: ashwiniethiraj/recommendationservice:v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: AD_SERVICE_ADDR
              value: adservice:9555
            - name: DISABLE_PROFILER
              value: "true"
         
      imagePullSecrets:
        - name: ecr-secret
