name: cartservice-ci

on:
  pull_request:
    branches:
      - main

jobs:
  # ---------- Build & Unit Test ----------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # adjust if using 7.0 or 6.0

      - name: Restore dependencies
        run: |
          cd src
          dotnet restore cartservice.sln

      - name: Build
        run: |
          cd src
          dotnet build cartservice.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: |
          cd src/tests
          dotnet test cartservice.tests.csproj --no-restore --verbosity normal

  # ---------- Docker Build & Push ----------
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cartservice:${{ github.run_id }}

  # ---------- Update Kubernetes Manifest ----------
  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Checkout target branch
        run: |
          git fetch origin ${{ github.head_ref || github.ref_name }}
          git checkout ${{ github.head_ref || github.ref_name }}

      - name: Update image tag in Kubernetes manifest
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/cartservices:${{ github.run_id }}|" kubernetes/cartservice/deploy.yml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.email "ashwiniethiraj@gmail.com"
          git config user.name "ashwiniethiraj"
          git add kubernetes/cartservice/deploy.yml
          git commit -m "ci: update cartservice image tag" || echo "No changes to commit"
          git pull --rebase origin ${{ github.head_ref || github.ref_name }}
          git push origin HEAD:${{ github.head_ref || github.ref_name }}
